/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NodeRouteImport } from './routes/node'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as StartRouteImport } from './routes/start'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ApiIosProfileRouteImport } from './routes/api/ios-profile'
import { Route as ApiPasskeyRouteImport } from './routes/api/passkey'
import { Route as ApiRemoteRouteImport } from './routes/api/remote'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiArtTicketRouteImport } from './routes/api/art.$ticket'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStreamTicketRouteImport } from './routes/api/stream.$ticket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeRoute = NodeRouteImport.update({
  id: '/node',
  path: '/node',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIosProfileRoute = ApiIosProfileRouteImport.update({
  id: '/api/ios-profile',
  path: '/api/ios-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasskeyRoute = ApiPasskeyRouteImport.update({
  id: '/api/passkey',
  path: '/api/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteRoute = ApiRemoteRouteImport.update({
  id: '/api/remote',
  path: '/api/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtTicketRoute = ApiArtTicketRouteImport.update({
  id: '/api/art/$ticket',
  path: '/api/art/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamTicketRoute = ApiStreamTicketRouteImport.update({
  id: '/api/stream/$ticket',
  path: '/api/stream/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compatibility': typeof CompatibilityRoute
  '/connect': typeof ConnectRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/node': typeof NodeRoute
  '/remote': typeof RemoteRoute
  '/start': typeof StartRoute
  '/tv': typeof TvRoute
  '/api/ios-profile': typeof ApiIosProfileRoute
  '/api/passkey': typeof ApiPasskeyRoute
  '/api/remote': typeof ApiRemoteRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/api/art/$ticket': typeof ApiArtTicketRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/$ticket': typeof ApiStreamTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compatibility': typeof CompatibilityRoute
  '/connect': typeof ConnectRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/node': typeof NodeRoute
  '/remote': typeof RemoteRoute
  '/start': typeof StartRoute
  '/tv': typeof TvRoute
  '/api/ios-profile': typeof ApiIosProfileRoute
  '/api/passkey': typeof ApiPasskeyRoute
  '/api/remote': typeof ApiRemoteRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/api/art/$ticket': typeof ApiArtTicketRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/$ticket': typeof ApiStreamTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compatibility': typeof CompatibilityRoute
  '/connect': typeof ConnectRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/node': typeof NodeRoute
  '/remote': typeof RemoteRoute
  '/start': typeof StartRoute
  '/tv': typeof TvRoute
  '/api/ios-profile': typeof ApiIosProfileRoute
  '/api/passkey': typeof ApiPasskeyRoute
  '/api/remote': typeof ApiRemoteRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/api/art/$ticket': typeof ApiArtTicketRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/$ticket': typeof ApiStreamTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/compatibility'
    | '/connect'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/node'
    | '/remote'
    | '/start'
    | '/tv'
    | '/api/ios-profile'
    | '/api/passkey'
    | '/api/remote'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/api/art/$ticket'
    | '/api/auth/$'
    | '/api/stream/$ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/compatibility'
    | '/connect'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/node'
    | '/remote'
    | '/start'
    | '/tv'
    | '/api/ios-profile'
    | '/api/passkey'
    | '/api/remote'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/api/art/$ticket'
    | '/api/auth/$'
    | '/api/stream/$ticket'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/compatibility'
    | '/connect'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/node'
    | '/remote'
    | '/start'
    | '/tv'
    | '/api/ios-profile'
    | '/api/passkey'
    | '/api/remote'
    | '/legal/privacy'
    | '/legal/terms'
    | '/s/$token'
    | '/api/art/$ticket'
    | '/api/auth/$'
    | '/api/stream/$ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CompatibilityRoute: typeof CompatibilityRoute
  ConnectRoute: typeof ConnectRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NodeRoute: typeof NodeRoute
  RemoteRoute: typeof RemoteRoute
  StartRoute: typeof StartRoute
  TvRoute: typeof TvRoute
  ApiIosProfileRoute: typeof ApiIosProfileRoute
  ApiPasskeyRoute: typeof ApiPasskeyRoute
  ApiRemoteRoute: typeof ApiRemoteRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  STokenRoute: typeof STokenRoute
  ApiArtTicketRoute: typeof ApiArtTicketRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStreamTicketRoute: typeof ApiStreamTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node': {
      id: '/node'
      path: '/node'
      fullPath: '/node'
      preLoaderRoute: typeof NodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ios-profile': {
      id: '/api/ios-profile'
      path: '/api/ios-profile'
      fullPath: '/api/ios-profile'
      preLoaderRoute: typeof ApiIosProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passkey': {
      id: '/api/passkey'
      path: '/api/passkey'
      fullPath: '/api/passkey'
      preLoaderRoute: typeof ApiPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote': {
      id: '/api/remote'
      path: '/api/remote'
      fullPath: '/api/remote'
      preLoaderRoute: typeof ApiRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/art/$ticket': {
      id: '/api/art/$ticket'
      path: '/api/art/$ticket'
      fullPath: '/api/art/$ticket'
      preLoaderRoute: typeof ApiArtTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$ticket': {
      id: '/api/stream/$ticket'
      path: '/api/stream/$ticket'
      fullPath: '/api/stream/$ticket'
      preLoaderRoute: typeof ApiStreamTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CompatibilityRoute: CompatibilityRoute,
  ConnectRoute: ConnectRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NodeRoute: NodeRoute,
  RemoteRoute: RemoteRoute,
  StartRoute: StartRoute,
  TvRoute: TvRoute,
  ApiIosProfileRoute: ApiIosProfileRoute,
  ApiPasskeyRoute: ApiPasskeyRoute,
  ApiRemoteRoute: ApiRemoteRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  STokenRoute: STokenRoute,
  ApiArtTicketRoute: ApiArtTicketRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStreamTicketRoute: ApiStreamTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
